version: 2
jobs:
  plan:             
    docker:
      - image: hashicorp/terraform
    steps:      
      - checkout
      - run: terraform init
      - run: terraform plan 
  apply: 
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve -input=false
workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan
      - apply:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
