version: 2
jobs:
  plan:             
    docker:
      - image: hashicorp/terraform
    steps:      
      - checkout
      - run: terraform init
      - run: terraform plan 
  apply: 
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve -input=false
workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan
      - apply-approve:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - apply-approve
#          filters:
#            branches:
#              only: master
